#!/usr/bin/env python3
"""
Build script for rboot bootloader.
Replaces esptool2 with Python-based ELF section extraction
and ESP8266 binary image generation.

Usage: python build_rboot.py

Requires xtensa-lx106-elf-gcc, objcopy, readelf in PATH or
PlatformIO toolchain at the default location.
"""

import os
import sys
import struct
import subprocess
from pathlib import Path

# === Configuration ===
SCRIPT_DIR = Path(__file__).parent.resolve()
BUILD_DIR = SCRIPT_DIR / "build"
SDK_LD_DIR = Path(
    os.environ.get("SDK_LD_DIR", ""),
    # Default: PlatformIO ESP8266 Arduino framework
    r"C:\Users\HXY\.platformio\packages\framework-arduinoespressif8266\tools\sdk\ld",
)

# Find xtensa toolchain
TOOLCHAIN_DIR = Path(
    os.environ.get("XTENSA_BINDIR", ""),
    r"C:\Users\HXY\.platformio\packages\toolchain-xtensa\bin",
)
CC = str(TOOLCHAIN_DIR / "xtensa-lx106-elf-gcc.exe")
OBJCOPY = str(TOOLCHAIN_DIR / "xtensa-lx106-elf-objcopy.exe")
READELF = str(TOOLCHAIN_DIR / "xtensa-lx106-elf-readelf.exe")

# Compiler flags (from rboot Makefile)
CFLAGS = " ".join([
    "-Os",
    "-Wpointer-arith",
    "-Wundef",
    "-Werror",
    "-Wl,-EL",
    "-fno-inline-functions",
    "-nostdlib",
    "-mlongcalls",
    "-mtext-section-literals",
    "-D__ets__",
    "-DICACHE_FLASH",
    "-DBOOT_BIG_FLASH",      # Enable big flash support for 4MB
    "-DMAX_ROMS=2",          # We only need 2 ROMs
])
LDFLAGS = "-nostdlib -u call_user_start -Wl,-static"

# Flash parameters for the final binary
FLASH_MODE = 3   # DOUT (matches our firmware)
FLASH_SIZE_FREQ = 0x40  # 4MB (32Mbit) / 40MHz


def run(cmd, desc=""):
    """Run a command and check for errors."""
    if desc:
        print(f"  {desc}")
    print(f"  > {cmd}")
    result = subprocess.run(cmd, shell=True, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"  ERROR: {result.stderr}")
        sys.exit(1)
    return result.stdout


def extract_section_binary(elf_path, section_name, output_path):
    """Extract a raw binary section from an ELF file using objcopy."""
    cmd = f'"{OBJCOPY}" -O binary --only-section .{section_name} "{elf_path}" "{output_path}"'
    run(cmd, f"Extract .{section_name} from {elf_path.name}")


def get_section_info(elf_path, section_name):
    """Get section address and size from ELF using readelf."""
    cmd = f'"{READELF}" -S "{elf_path}"'
    output = run(cmd, f"Get section info from {elf_path.name}")
    target = f".{section_name}"
    for line in output.split("\n"):
        if target in line and "PROGBITS" in line:
            parts = line.split()
            for i, p in enumerate(parts):
                if p == target:
                    if i + 3 < len(parts):
                        addr = int(parts[i + 2], 16)
                        size = int(parts[i + 4], 16)
                        return addr, size
    return None, None


def get_entry_point(elf_path):
    """Get entry point from ELF."""
    cmd = f'"{READELF}" -h "{elf_path}"'
    output = run(cmd)
    for line in output.split("\n"):
        if "Entry point" in line:
            return int(line.split(":")[1].strip(), 16)
    return 0


def generate_header(stage2a_elf, header_path):
    """
    Replace esptool2 -header mode.
    Extract .text section from stage2a ELF and generate C header file.
    """
    print("[STEP 3] Generating rboot-hex2a.h from stage2a ELF...")

    # Extract raw binary of .text section
    text_bin = BUILD_DIR / "stage2a_text.bin"
    extract_section_binary(stage2a_elf, "text", text_bin)

    # Get section address
    addr, size = get_section_info(stage2a_elf, "text")
    if addr is None:
        print("  ERROR: Could not find .text section in stage2a ELF")
        sys.exit(1)

    entry = get_entry_point(stage2a_elf)
    print(f"  .text addr=0x{addr:08x} size={size} entry=0x{entry:08x}")

    # Read the binary data
    with open(text_bin, "rb") as f:
        data = f.read()

    # Generate C header
    hex_bytes = ", ".join(f"0x{b:02x}" for b in data)
    header_content = f"""\
// Auto-generated by build_rboot.py
// rboot stage2a loader binary

const uint32_t _text_addr = 0x{addr:08x};
const uint32_t _text_len = {len(data)};
const uint8_t _text_data[{len(data)}] = {{{hex_bytes}}};
const uint32_t entry_addr = 0x{entry:08x};
"""

    with open(header_path, "w") as f:
        f.write(header_content)
    print(f"  Written: {header_path} ({len(data)} bytes)")


def generate_esp_image(elf_path, output_path, sections, flash_mode=3, flash_size_freq=0x40):
    """
    Replace esptool2 -bin -boot0 mode.
    Generate ESP8266 binary image from ELF sections.

    ESP8266 image format:
    - Magic: 0xE9 (1 byte)
    - Num segments (1 byte)
    - Flash mode (1 byte)
    - Flash size/freq (1 byte)
    - Entry point (4 bytes, LE)
    - Per segment: load addr (4B) + size (4B) + data
    - Pad to 16 bytes
    - Checksum (1 byte, XOR of all segment data)
    """
    print(f"[STEP 6] Generating ESP8266 binary image...")

    entry = get_entry_point(elf_path)
    print(f"  Entry point: 0x{entry:08x}")

    segment_data = []
    for sec_name in sections:
        sec_bin = BUILD_DIR / f"rboot_{sec_name}.bin"
        extract_section_binary(elf_path, sec_name, sec_bin)

        addr, size = get_section_info(elf_path, sec_name)
        if addr is None:
            print(f"  WARNING: Section .{sec_name} not found, skipping")
            continue

        with open(sec_bin, "rb") as f:
            data = f.read()

        if len(data) == 0:
            print(f"  Section .{sec_name} is empty, skipping")
            continue

        print(f"  Section .{sec_name}: addr=0x{addr:08x} size={len(data)}")
        segment_data.append((addr, data))

    # Build image
    image = bytearray()
    # Header
    image.append(0xE9)  # magic
    image.append(len(segment_data))  # segment count
    image.append(flash_mode)  # flash mode
    image.append(flash_size_freq)  # flash size/freq
    image.extend(struct.pack("<I", entry))  # entry point

    # Segments
    all_data = bytearray()
    for addr, data in segment_data:
        image.extend(struct.pack("<I", addr))  # load address
        image.extend(struct.pack("<I", len(data)))  # size
        image.extend(data)
        all_data.extend(data)

    # Pad to 16-byte boundary
    padding = (16 - (len(image) % 16)) % 16
    # The checksum byte position is at the next 16-byte boundary after all data
    # But we need to add padding bytes first (0xFF or the actual flash data)
    # Actually, the padding is done with the existing flash content,
    # but for our image we pad with 0xFF

    # Calculate checksum (XOR of all segment data)
    chksum = 0xEF  # CHKSUM_INIT
    for b in all_data:
        chksum ^= b

    # The checksum is placed at byte position aligned to 16,
    # after all segments. But the actual format has the checksum
    # at the very end of the padded segment data.
    # esptool2 places it after rounding up to 16 bytes
    padded_len = (len(image) + 15) & ~15
    image.extend(b'\xFF' * (padded_len - len(image)))
    image.append(chksum)

    with open(output_path, "wb") as f:
        f.write(image)
    print(f"  Written: {output_path} ({len(image)} bytes)")
    print(f"  Checksum: 0x{chksum:02x}")


def main():
    print("=" * 60)
    print("rboot Bootloader Build Script")
    print("=" * 60)
    print(f"Build dir: {BUILD_DIR}")
    print(f"Toolchain: {TOOLCHAIN_DIR}")
    print(f"SDK LD:    {SDK_LD_DIR}")
    print()

    # Verify toolchain
    if not Path(CC).exists():
        print(f"ERROR: Compiler not found: {CC}")
        print("Set XTENSA_BINDIR environment variable or install PlatformIO ESP8266 toolchain")
        sys.exit(1)

    BUILD_DIR.mkdir(parents=True, exist_ok=True)

    ld_include = f'-L"{SDK_LD_DIR}"'

    # ================================================================
    # STEP 1: Compile rboot-stage2a.c
    # ================================================================
    print("[STEP 1] Compiling rboot-stage2a.c...")
    stage2a_o = BUILD_DIR / "rboot-stage2a.o"
    cmd = (
        f'"{CC}" {CFLAGS}'
        f' -I"{SCRIPT_DIR}"'
        f' -c "{SCRIPT_DIR / "rboot-stage2a.c"}"'
        f' -o "{stage2a_o}"'
    )
    run(cmd)

    # ================================================================
    # STEP 2: Link rboot-stage2a.o → rboot-stage2a.elf
    # ================================================================
    print("[STEP 2] Linking rboot-stage2a.elf...")
    stage2a_elf = BUILD_DIR / "rboot-stage2a.elf"
    cmd = (
        f'"{CC}" -T"{SCRIPT_DIR / "rboot-stage2a.ld"}" {LDFLAGS} {ld_include}'
        f' -Wl,--start-group "{stage2a_o}" -Wl,--end-group'
        f' -o "{stage2a_elf}"'
    )
    run(cmd)

    # ================================================================
    # STEP 3: Generate rboot-hex2a.h (esptool2 -header replacement)
    # ================================================================
    hex2a_h = BUILD_DIR / "rboot-hex2a.h"
    generate_header(stage2a_elf, hex2a_h)

    # ================================================================
    # STEP 4: Compile rboot.c (with generated header)
    # ================================================================
    print("[STEP 4] Compiling rboot.c...")
    rboot_o = BUILD_DIR / "rboot.o"
    cmd = (
        f'"{CC}" {CFLAGS}'
        f' -I"{SCRIPT_DIR}"'
        f' -I"{BUILD_DIR}"'  # for rboot-hex2a.h
        f' -c "{SCRIPT_DIR / "rboot.c"}"'
        f' -o "{rboot_o}"'
    )
    run(cmd)

    # ================================================================
    # STEP 5: Link rboot.o → rboot.elf
    # ================================================================
    print("[STEP 5] Linking rboot.elf...")
    rboot_elf = BUILD_DIR / "rboot.elf"
    cmd = (
        f'"{CC}" -T"{SCRIPT_DIR / "eagle.app.v6.ld"}" {LDFLAGS} {ld_include}'
        f' -Wl,--start-group "{rboot_o}" -Wl,--end-group'
        f' -o "{rboot_elf}"'
    )
    run(cmd)

    # ================================================================
    # STEP 6: Generate rboot.bin (esptool2 -bin -boot0 replacement)
    # ================================================================
    rboot_bin = SCRIPT_DIR / "rboot.bin"
    generate_esp_image(rboot_elf, rboot_bin, ["text", "rodata"],
                       flash_mode=FLASH_MODE, flash_size_freq=FLASH_SIZE_FREQ)

    print()
    print("=" * 60)
    print(f"SUCCESS! rboot.bin: {rboot_bin}")
    print(f"Size: {rboot_bin.stat().st_size} bytes")
    print()
    print("Flash command:")
    print(f"  esptool.py --port COMx --baud 115200 write-flash 0x0000 rboot.bin")
    print("=" * 60)


if __name__ == "__main__":
    main()
