; IR Mini V105 — 万能红外遥控器
; rboot 双分区 OTA + iOS 风格 WebUI + 空调控制 + MQTT + 传感器

[platformio]
default_envs = rom0

[env_base]
platform = espressif8266@4.2.1
board = nodemcuv2
framework = arduino
lib_deps =
    crankyoldgit/IRremoteESP8266@^2.8.6
    knolleary/PubSubClient@^2.8
    milesburton/DallasTemperature@^3.11.0
build_flags =
    -DPIO_FRAMEWORK_ARDUINO_LWIP2_LOW_MEMORY
    -DVTABLES_IN_FLASH
    -DMQTT_MAX_PACKET_SIZE=1024
    -I rboot
upload_speed = 115200
upload_port = COM10
monitor_speed = 115200

; ROM 0 (日常编译 + USB-TTL 刷写)
[env:rom0]
extends = env_base
board_build.ldscript = ld/rboot-ROM0.ld

; ROM 1 (OTA 更新固件)
[env:rom1]
extends = env_base
board_build.ldscript = ld/rboot-ROM1.ld
